---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: ingress-nginx
  namespace: ingress
  labels:
    acm-app: ingress-nginx
spec:
  selector:
    matchLabels:
      acm-app: ingress-nginx
