---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: prometheus-stack
  namespace: acm-poc-fo-gitops
  labels:
    acm-app: prometheus-stack
spec:
  selector:
    matchLabels:
      acm-app: prometheus-stack
