apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: ingress-nginx-dev-westeu-1
  namespace: ingress
  labels:
    acm-app: ingress-nginx
spec:
  channel: acm-poc-fo-gitops-ch-fo-helm/channel
  name: ingress-nginx
  packageFilter:
    version: "0.1.0"
  placement:
    clusterSelector:
      matchLabels:
        zone: dev-westeu-1
  packageOverrides:
  - packageName: ingress-nginx
    packageOverrides:
      - path: spec
        value:
          ingress-nginx:
            controller:
              service:
                annotations:
                  service.beta.kubernetes.io/azure-load-balancer-internal: "true"
