apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: ingress-nginx-dev-westeu-1
  namespace: ingress
  labels:
    acm-app: ingress-nginx
spec:
  channel: acm-poc-fo-gitops-ch-ingress-nginx/channel
  name: ingress-nginx
  packageFilter:
    version: "3.23.0"
  placement:
    clusterSelector:
      matchLabels:
        zone: dev-westeu-1
  packageOverrides:
  - packageName: ingress-nginx
    packageOverrides:
      - path: spec
        value:
          controller:
            service:
              annotations:
                service.beta.kubernetes.io/azure-load-balancer-internal: "true"
            admissionWebhooks:
              enabled: false
            updateStrategy:
              rollingUpdate:
                maxUnavailable: 1
              type: RollingUpdate
            config:
              keep-alive: 75s
              keep-alive-requests: "100"
              log-format-escape-json: "true"
              log-format-upstream: |-
                {"time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr",
                "x-forward-for": "$proxy_add_x_forwarded_for", "request_id": "$req_id",
                "remote_user": "$remote_user", "bytes_sent": $bytes_sent,
                "request_time": $request_time, "status":$status, "vhost": "$host",
                "request_proto": "$server_protocol", "path": "$uri",
                "request_query": "$args", "request_length": $request_length,
                "duration": $request_time,"method": "$request_method",
                "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent",
                "ff-trace-id": "$http_ff_trace_id"}
              proxy-body-size: 50m
              proxy-buffer-size: 16k
              server-tokens: "false"
              ssl-redirect: "false"
            metrics:
              enabled: true
              service:
                type: ClusterIP
                clusterIP: "None"
              serviceMonitor:
                enabled: true
            publishService:
              enabled: true
          rbac:
            create: true
