apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: prometheus-stack-dev-westeu-1
  namespace: acm-poc-fo-gitops
  labels:
    acm-app: prometheus-stack
spec:
  channel: acm-poc-fo-gitops-ch-fo-helm/channel
  name: kube-prometheus-stack
  packageFilter:
    version: "0.1.0"
  placement:
    clusterSelector:
      matchLabels:
        zone: dev-westeu-1
  packageOverrides:
  - packageName: prometheus-stack
    packageOverrides:
      - path: spec
        value:
          kube-prometheus-stack:
            prometheus:
              ingress:
                enabled: true
                hosts:
                  - prometheus.dev
            grafana:
              ingress:
                enabled: true
                hosts:
                  - grafana.dev
